# ================================================================
# Gainz — project.yml
# XcodeGen manifest that builds an iOS-first, Swift-PM modular
# workspace with CI-grade scripts, watchOS hooks, and Core ML
# readiness. Tweak identifiers/paths as needed before first run.
# ================================================================

name: Gainz
options:
  bundleIdPrefix: app.gainz
  xcodeVersion: "15.3"
  deploymentTarget:
    iOS: "17.0"
  postGenCommand: |
    # Auto-resolve SPMs after generation
    xcodebuild -resolvePackageDependencies -project Gainz.xcodeproj

configs:
  Debug: debug
  Release: release

settings:
  base:
    SWIFT_VERSION: "5.9"
    ENABLE_PREVIEWS: YES
    CODE_SIGN_STYLE: Automatic
    DEVELOPMENT_TEAM: YOUR_TEAM_ID   # ← replace
    MARKETING_VERSION: "0.1.0"
    CURRENT_PROJECT_VERSION: 1
    IPHONEOS_DEPLOYMENT_TARGET: $(DEPLOYMENT_TARGET)
    OTHER_SWIFT_FLAGS[config=Debug]: "-Xfrontend -warn-long-function-bodies=200"

packages:
  Algorithms:
    url: https://github.com/apple/swift-algorithms
    from: 1.2.0
  Collections:
    url: https://github.com/apple/swift-collections
    from: 1.1.0
  SwiftLintPlugin:
    url: https://github.com/realm/SwiftLint
    exact: 0.55.0

targets:
  # ──────────────────────────────────────────────────────────────
  Gainz:
    platform: iOS
    type: application
    deploymentTarget: "17.0"
    sources: [App/Sources]
    resources: [App/Resources]
    info: App/Supporting/Info.plist
    entitlements: App/Supporting/Gainz.entitlements
    dependencies:
      - target: CoreKit
      - package: Algorithms
      - package: Collections
    settings:
      base:
        TARGETED_DEVICE_FAMILY: "1"      # iPhone only for now
    scripts:
      - name: SwiftLint
        basedOnDependencyAnalysis: false
        script: |
          if which swiftlint >/dev/null; then
            swiftlint --strict
          else
            echo "warning: SwiftLint not installed"
          fi
      - name: SwiftFormat
        basedOnDependencyAnalysis: false
        script: |
          if which swiftformat >/dev/null; then
            swiftformat --lint .
          else
            echo "warning: SwiftFormat not installed"
          fi
      - name: Increment Build Number
        script: |
          buildNumber=$(git rev-list --count HEAD)
          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $buildNumber" "${TARGET_BUILD_DIR}/${INFOPLIST_PATH}"

  CoreKit:
    platform: iOS
    type: framework
    deploymentTarget: "17.0"
    sources: [CoreKit/Sources]
    dependencies:
      - package: Collections

  GainzTests:
    platform: iOS
    type: bundle.unit-test
    deploymentTarget: "17.0"
    sources: [Tests]
    dependencies:
      - target: Gainz
    settings:
      base:
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/Gainz.app/Gainz"

schemes:
  Gainz:
    build:
      targets:
        Gainz: all
    run:
      config: Debug
    test:
      targets:
        - GainzTests
    archive:
      config: Release
    profile:
      config: Release

