# .github/workflows/release.yml
# Gainz — Continuous Delivery pipeline
# Triggers on every semver tag (e.g. v1.2.0) pushed to main.

name: 🚀 Release

on:
  push:
    tags:
      - 'v*.*.*'       # semantic version tags only

env:
  XCODE_VERSION: '16.0'
  IOS_SIM: 'iPhone 15'
  SCHEME: 'Gainz'
  WORKSPACE: 'Gainz.xcworkspace'

jobs:
  build-test:
    name: 🔨 Build & Test
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ env.XCODE_VERSION }}

      - name: Restore SwiftPM cache
        uses: actions/cache@v4
        with:
          path: |
            ~/Library/Developer/Xcode/DerivedData
            .build
          key: spm-${{ runner.os }}-${{ hashFiles('**/Package.resolved') }}

      - name: Resolve dependencies
        run: xcodebuild -resolvePackageDependencies -workspace "$WORKSPACE" -scheme "$SCHEME"

      - name: Build & run tests
        run: xcodebuild \
          -workspace "$WORKSPACE" \
          -scheme "$SCHEME" \
          -destination "platform=iOS Simulator,name=$IOS_SIM,OS=latest" \
          -configuration Release \
          -parallel-testing-enabled YES \
          -enableCodeCoverage YES \
          clean test | xcpretty && bash <(curl -Ls https://coverage.codacy.com/get.sh)

  release:
    name: 📦 TestFlight & GitHub Release
    needs: build-test
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ env.XCODE_VERSION }}

      - name: Decrypt certificates
        uses: apple-actions/import-codesign-certs@v3
        with:
          p12-file-base64: ${{ secrets.APPSTORE_P12 }}
          p12-password: ${{ secrets.APPSTORE_P12_PASSWORD }}
          keychain-password: ${{ secrets.KEYCHAIN_PASSWORD }}

      - name: Install Fastlane
        run: sudo gem install fastlane -NV

      - name: Build & upload to TestFlight
        run: |
          bundle install --path vendor/bundle
          bundle exec fastlane ios beta
        env:
          APP_STORE_CONNECT_API_KEY_KEY_ID: ${{ secrets.APP_STORE_KEY_ID }}
          APP_STORE_CONNECT_API_KEY_ISSUER_ID: ${{ secrets.APP_STORE_ISSUER_ID }}
          APP_STORE_CONNECT_API_KEY_KEY: ${{ secrets.APP_STORE_PRIVATE_KEY }}
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_PASSWORD }}

      - name: Generate changelog from commits
        id: changelog
        uses: mikepenz/release-changelog-builder-action@v4
        with:
          configuration: .github/changelog-config.json

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: ${{ steps.changelog.outputs.changelog }}
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
